### Create User
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
    "name": "test",
    "email": "test@test.com"
}

### Delete User
DELETE http://localhost:8080/api/v1/user/delete/{{userId}}

### List Users
GET http://localhost:8080/api/v1/user/list

### Find User by id
GET http://localhost:8080/api/v1/user/{{userId}}

### Create expense
POST http://localhost:8080/api/v1/expense/{{userId}}
Content-Type: application/json

{
  "date": "2026-09-07",
  "reason": "Test",
  "value": 10,
  "userId": 1
}

### Delete expense
DELETE http://localhost:8080/api/v1/expense/{{userId}}/delete/{{expenseId}}

### List expenses
GET http://localhost:8080/api/v1/expense/{{userId}}/list

### Find expense by id
GET http://localhost:8080/api/v1/expense/{{userId}}/{{expenseId}}