CREATE TABLE expense
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date    date,
    reason  VARCHAR(255),
    value   DOUBLE PRECISION                        NOT NULL,
    vat     DOUBLE PRECISION,
    user_id BIGINT,
    CONSTRAINT pk_expense PRIMARY KEY (id)
);

CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    email VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE expense
    ADD CONSTRAINT FK_EXPENSE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);